CREATE TABLE IF NOT EXISTS feed (id INTEGER PRIMARY KEY CHECK(id=1), captured INTEGER NOT NULL, snapshot TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS encounters (id TEXT PRIMARY KEY, name TEXT NOT NULL, identity TEXT NOT NULL, area TEXT NOT NULL, x INTEGER NOT NULL, y INTEGER NOT NULL, plane INTEGER NOT NULL, relationship TEXT NOT NULL, first INTEGER NOT NULL, last INTEGER NOT NULL);
CREATE INDEX IF NOT EXISTS encounter_last ON encounters(last);
