import {test} from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker from './worker.js';

function fixture(){
  const db=new DatabaseSync(':memory:');db.exec(readFileSync(new URL('schema.sql',import.meta.url),'utf8'));
  const env={UPLOAD_TOKEN:'fixture-token-never-used-in-production',DB:{prepare(sql){let args=[];return {bind(...v){args=v;return this;},async first(){return db.prepare(sql).get(...args)||null;},async all(){return {results:db.prepare(sql).all(...args)};},async run(){return db.prepare(sql).run(...args);}};},async batch(commands){db.exec('BEGIN');try{for(const c of commands)await c.run();db.exec('COMMIT');}catch(e){db.exec('ROLLBACK');throw e;}}}};
  const p={id:'encounter-1',name:'<b>Example</b>',identity:'example',area:'surface',position:[3100,3800,0],relationship:'friend',firstSeenAt:Date.now()-60000,lastSeenAt:Date.now()-500};
  const body={capturedAt:Date.now(),players:[{id:'live-1',name:p.name,identity:p.identity,position:p.position,relationship:p.relationship,lastSeenAt:p.lastSeenAt,observed:true}],clients:[],encounters:[p],removed:[]};
  const get=async path=>worker.fetch(new Request('https://fixture.test'+path),env);
  const post=async (value=body,headers={Authorization:'Bearer '+env.UPLOAD_TOKEN})=>worker.fetch(new Request('https://fixture.test/v1/publish',{method:'POST',headers,body:JSON.stringify(value)}),env);
  return {db,env,p,body,get,post};
}
test('authenticated upload feeds public reads without credentials or controls',async()=>{const f=fixture();assert.equal((await f.post()).status,200);const r=await(await f.get('/v1/state')).json();assert.equal(r.players.length,1);assert.equal(r.players[0].name,'<b>Example</b>');assert.equal(r.online,true);assert.ok(!JSON.stringify(r).includes(f.env.UPLOAD_TOKEN));for(const path of ['/api/map/browser','/api/map/actions','/api/map/control/acquire','/v1/publish'])assert.equal((await f.get(path)).status,404);f.db.close();});
test('unauthorized and browser-origin uploads are rejected',async()=>{const f=fixture();assert.equal((await f.post(f.body,{})).status,401);assert.equal((await f.post(f.body,{Authorization:'Bearer wrong'})).status,401);assert.equal((await f.post(f.body,{Authorization:'Bearer '+f.env.UPLOAD_TOKEN,Origin:'https://www.oskariozan.com'})).status,401);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM feed').get().n,0);f.db.close();});
test('malformed tail and injected control fields cannot partially write',async()=>{const f=fixture();for(const changed of [{...f.body,token:'private'},{...f.body,encounters:[f.p,{...f.p,id:'invalid',position:[true,2,0]}]},{...f.body,clients:[{id:'a',name:'b',role:'LEADER',position:[1,2,0],lastSeenAt:Date.now(),navigation:{token:'bad'}}]}])assert.equal((await f.post(changed)).status,400);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM encounters').get().n,0);f.db.close();});
test('history upserts one encounter, separates IDs and supports removal',async()=>{const f=fixture();await f.post();f.p.lastSeenAt+=100;await f.post();assert.equal(f.db.prepare('SELECT COUNT(*) n FROM encounters').get().n,1);await f.post({...f.body,encounters:[{...f.p,id:'encounter-2',area:'aquanite',position:[3050,10300,0]}]});let h=await(await f.get('/v1/history?windowSeconds=43200')).json();assert.equal(h.encounters.length,2);await f.post({...f.body,encounters:[],removed:['encounter-1']});h=await(await f.get('/v1/history?windowSeconds=43200')).json();assert.equal(h.encounters.length,1);f.db.close();});
test('twelve hour bounds, scheduled expiry and stale uploader',async()=>{const f=fixture();await f.post();assert.equal((await f.post({...f.body,capturedAt:f.body.capturedAt-1})).status,409);assert.equal((await f.get('/v1/state?windowSeconds=43201')).status,400);f.db.prepare('UPDATE encounters SET last=?').run(Date.now()-43200001);assert.equal((await(await f.get('/v1/history?windowSeconds=43200')).json()).encounters.length,0);await worker.scheduled(null,f.env);assert.equal(f.db.prepare('SELECT COUNT(*) n FROM encounters').get().n,0);f.db.close();});
test('offline snapshots cannot keep live markers observed or clients visible',async()=>{const f=fixture();await f.post();f.db.prepare('UPDATE feed SET captured=?').run(Date.now()-11000);const r=await(await f.get('/v1/state')).json();assert.equal(r.online,false);assert.equal(r.players[0].observed,false);assert.deepEqual(r.clients,[]);f.db.close();});
test('multiple live observers remain distinct; history summary is deduplicated',async()=>{const f=fixture();f.body.players.push({...f.body.players[0],id:'live-2'});await f.post();const r=await(await f.get('/v1/state')).json();assert.equal(r.players.length,2);const h=await(await f.get('/v1/hotspots?windowSeconds=43200')).json();assert.equal(h.cells[0].uniquePlayers,1);assert.equal(h.cells[0].encounters,1);f.db.close();});
test('invalid public query and oversized stream fail cleanly',async()=>{const f=fixture();for(const q of ['windowSeconds=nan','windowSeconds=0','windowSeconds=30&windowSeconds=60','token=oops','offset=-1'])assert.equal((await f.get('/v1/history?'+q)).status,400);assert.equal((await f.post('x'.repeat(1048577))).status,413);f.db.close();});

test('different underground areas do not erase each other',async()=>{const f=fixture();f.p.area='aquanite';f.p.position=[3050,10300,0];f.body.players[0].position=[3250,10350,0];await f.post();const r=await(await f.get('/v1/state')).json();assert.equal(r.players.length,2);f.db.close();});
